-- pgTAP: which records a conflict may name, and who may act on staff-account
-- and stock conflicts (audit finding 4.9)
-- Migration under test:
--   supabase/migrations/20260927100100_conflict_record_types.sql
-- Run with `supabase test db` (see supabase/tests/README.md). Fixtures are
-- created below and everything is rolled back at the end.
--
-- The table's shape differs between databases: `supabase db reset` builds
-- the 20251024080033 table (text id without a default, patient_id NOT NULL)
-- plus later columns, while 20260125094038 creates it with a uuid id and no
-- patient_id. So inserts are generated by pgtap_conflict_insert() below:
-- it names only the columns this database has (columns it leaves out keep
-- their defaults) and reads the values from one JSON object. Only columns
-- both shapes have are updated. The reset shape has no updated_at column,
-- which the existing update_conflict_resolutions_timestamp trigger sets on
-- every UPDATE, so it is added here (inside the transaction) when missing.

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;

SELECT plan(28);

-- ---------------------------------------------------------------------------
-- Fixtures (as the migration owner: guards and row-level security do not
-- apply to this role)
-- ---------------------------------------------------------------------------
ALTER TABLE public.conflict_resolutions
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

INSERT INTO public.app_users (id, full_name, role) VALUES
  ('22220000-0000-4000-8000-000000000001', 'pgTAP admin',      'admin'),
  ('22220000-0000-4000-8000-000000000002', 'pgTAP nurse',      'nurse'),
  ('22220000-0000-4000-8000-000000000003', 'pgTAP doctor',     'doctor'),
  ('22220000-0000-4000-8000-000000000004', 'pgTAP pharmacist', 'pharmacist');

INSERT INTO public.patients (id, given_name, family_name, phone) VALUES
  ('pgtap-conflict-p1', 'Ada', 'Conflict', '08000000091');

-- Values for every NOT NULL column either shape has.
CREATE TEMP TABLE pgtap_conflict_base (j jsonb) ON COMMIT DROP;
INSERT INTO pgtap_conflict_base VALUES (jsonb_build_object(
  'patient_id', 'pgtap-conflict-p1',
  'conflict_type', 'sync_conflict',
  'entity_id', 'pgtap-conflict-record',
  'candidate_ids', '[]'::jsonb,
  'status', 'pending',
  'priority', 'medium',
  'phi_sensitivity', 'low',
  'conflict_details', '{}'::jsonb,
  'created_at', '2026-09-27T10:00:00Z',
  'updated_at', '2026-09-27T10:00:00Z'));
GRANT SELECT ON pgtap_conflict_base TO PUBLIC;

-- The INSERT statement for the given conflicts (a JSON array of objects,
-- each added to the base values), naming only the columns
-- public.conflict_resolutions has in this database.
CREATE FUNCTION pg_temp.pgtap_conflict_insert(p_rows jsonb)
RETURNS text
LANGUAGE sql
STABLE
AS $f$
  WITH r AS (
    SELECT (SELECT j FROM pgtap_conflict_base) || e AS j
      FROM jsonb_array_elements(p_rows) AS e
  )
  SELECT format(
    'INSERT INTO public.conflict_resolutions (%1$s) SELECT %1$s FROM jsonb_populate_recordset(NULL::public.conflict_resolutions, %2$L::jsonb)',
    (SELECT string_agg(quote_ident(a.attname), ', ' ORDER BY a.attnum)
       FROM pg_attribute AS a
      WHERE a.attrelid = 'public.conflict_resolutions'::regclass
        AND a.attnum > 0 AND NOT a.attisdropped
        AND EXISTS (SELECT 1 FROM r WHERE r.j ? a.attname)),
    (SELECT jsonb_agg(r.j) FROM r)::text);
$f$;

-- Existing conflicts to update.
DO $$ BEGIN EXECUTE pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0001","entity_type":"app_users"}]'); END $$;
DO $$ BEGIN EXECUTE pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0002","entity_type":"inventory"}]'); END $$;
DO $$ BEGIN EXECUTE pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0003","entity_type":"patients"}]'); END $$;

-- ---------------------------------------------------------------------------
-- The policy and the function
-- ---------------------------------------------------------------------------
SELECT ok(
  EXISTS (
    SELECT 1 FROM pg_policy
     WHERE polrelid = 'public.conflict_resolutions'::regclass
       AND polname = 'conflict_resolutions_insert_record_type'
       AND NOT polpermissive
       AND polcmd = 'a'
       AND polroles = ARRAY['authenticated'::regrole::oid]),
  'conflict_resolutions_insert_record_type is a RESTRICTIVE INSERT policy for authenticated');

SELECT ok(
  EXISTS (
    SELECT 1 FROM pg_policy
     WHERE polrelid = 'public.conflict_resolutions'::regclass
       AND polname = 'conflict_resolutions_insert'
       AND polpermissive),
  'the permissive conflict_resolutions_insert from 20260924110200 is still there');

SELECT ok(
  (SELECT NOT prosecdef
          AND 'search_path=public, pg_catalog' = ANY (proconfig)
     FROM pg_proc
    WHERE oid = 'public.app_conflict_approval_guard()'::regprocedure),
  'app_conflict_approval_guard stays SECURITY INVOKER with its search_path');

SELECT ok(
  NOT has_function_privilege('anon', 'public.app_conflict_approval_guard()', 'EXECUTE'),
  'anon cannot execute app_conflict_approval_guard');

-- ---------------------------------------------------------------------------
-- INSERT as an admin (resolve_conflicts, users, inventory)
-- ---------------------------------------------------------------------------
SET LOCAL ROLE authenticated;
SET LOCAL request.jwt.claims = '{"sub":"22220000-0000-4000-8000-000000000001","role":"authenticated"}';

SELECT lives_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0101","entity_type":"app_users"}]'),
  'an admin files a staff-account conflict');

SELECT lives_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0102","entity_type":"inventory"}]'),
  'an admin files a stock conflict');

SELECT lives_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0103","entity_type":"server_command"}]'),
  'an admin files a refused-change notice (server_command)');

-- ---------------------------------------------------------------------------
-- INSERT as a nurse (resolve_conflicts, no users, no inventory)
-- ---------------------------------------------------------------------------
SET LOCAL request.jwt.claims = '{"sub":"22220000-0000-4000-8000-000000000002","role":"authenticated"}';

SELECT lives_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0201","entity_type":"patients"}]'),
  'a nurse files a patient conflict');

SELECT lives_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0202","entity_type":"server_command"}]'),
  'a nurse files a refused-change notice (server_command needs no extra permission)');

SELECT throws_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0203","entity_type":"app_users"}]'),
  '42501', NULL,
  'a nurse cannot file a staff-account conflict (needs users)');

SELECT throws_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0204","entity_type":"inventory"}]'),
  '42501', NULL,
  'a nurse cannot file a stock conflict (needs inventory)');

SELECT throws_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0205","entity_type":"users"}]'),
  '42501', NULL,
  'a record type the app does not report (the local table name "users") is refused');

SELECT throws_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0206","entity_type":"lab_results"}]'),
  '42501', NULL,
  'a server table the sync adapter does not check for conflicts is refused');

SELECT throws_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0207","entity_type":null}]'),
  '42501', NULL,
  'a conflict with no record type is refused');

-- ---------------------------------------------------------------------------
-- INSERT as a doctor: every other listed type
-- ---------------------------------------------------------------------------
SET LOCAL request.jwt.claims = '{"sub":"22220000-0000-4000-8000-000000000003","role":"authenticated"}';

SELECT lives_ok(
  pg_temp.pgtap_conflict_insert('[
    {"id":"22220000-0000-4000-8000-0000000c0301","entity_type":"visits"},
    {"id":"22220000-0000-4000-8000-0000000c0302","entity_type":"vitals"},
    {"id":"22220000-0000-4000-8000-0000000c0303","entity_type":"consultations"},
    {"id":"22220000-0000-4000-8000-0000000c0304","entity_type":"dispenses"},
    {"id":"22220000-0000-4000-8000-0000000c0305","entity_type":"queue"},
    {"id":"22220000-0000-4000-8000-0000000c0306","entity_type":"patient_allergies"},
    {"id":"22220000-0000-4000-8000-0000000c0307","entity_type":"patient_preferences"}]'),
  'a doctor files conflicts for visits, vitals, consultations, dispenses, queue, allergies and preferences');

-- ---------------------------------------------------------------------------
-- INSERT as a pharmacist (inventory, no resolve_conflicts): the restrictive
-- policy never widens the permissive one
-- ---------------------------------------------------------------------------
SET LOCAL request.jwt.claims = '{"sub":"22220000-0000-4000-8000-000000000004","role":"authenticated"}';

SELECT throws_ok(
  pg_temp.pgtap_conflict_insert('[{"id":"22220000-0000-4000-8000-0000000c0401","entity_type":"inventory"}]'),
  '42501', NULL,
  'a pharmacist still cannot file conflicts (no resolve_conflicts)');

-- ---------------------------------------------------------------------------
-- UPDATE as a nurse: refused for staff-account and stock conflicts, whatever
-- the change; other conflicts unchanged
-- ---------------------------------------------------------------------------
SET LOCAL request.jwt.claims = '{"sub":"22220000-0000-4000-8000-000000000002","role":"authenticated"}';

SELECT throws_ok(
  $$UPDATE public.conflict_resolutions SET priority = 'high'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0001'$$,
  '42501', 'Staff account conflicts need the users permission',
  'a nurse cannot edit a staff-account conflict, even without deciding it');

SELECT throws_ok(
  $$UPDATE public.conflict_resolutions SET status = 'ignored'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0001'$$,
  '42501', 'Staff account conflicts need the users permission',
  'a nurse cannot close a staff-account conflict');

SELECT throws_ok(
  $$UPDATE public.conflict_resolutions
       SET entity_type = 'patients', status = 'ignored'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0001'$$,
  '42501', 'Staff account conflicts need the users permission',
  'changing entity_type in the same update does not get round the check (the stored type is read)');

SELECT throws_ok(
  $$UPDATE public.conflict_resolutions SET priority = 'high'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0002'$$,
  '42501', 'Stock conflicts need the inventory permission',
  'a nurse cannot edit a stock conflict');

SELECT throws_ok(
  $$UPDATE public.conflict_resolutions SET status = 'ignored'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0002'$$,
  '42501', 'Stock conflicts need the inventory permission',
  'a nurse cannot close a stock conflict');

SELECT lives_ok(
  $$UPDATE public.conflict_resolutions SET status = 'ignored'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0003'$$,
  'a nurse still closes a patient conflict');

-- ---------------------------------------------------------------------------
-- UPDATE as an admin
-- ---------------------------------------------------------------------------
SET LOCAL request.jwt.claims = '{"sub":"22220000-0000-4000-8000-000000000001","role":"authenticated"}';

SELECT lives_ok(
  $$UPDATE public.conflict_resolutions SET priority = 'high'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0002'$$,
  'an admin edits a stock conflict');

SELECT lives_ok(
  $$UPDATE public.conflict_resolutions SET status = 'ignored'
     WHERE id::text = '22220000-0000-4000-8000-0000000c0001'$$,
  'an admin closes a staff-account conflict');

RESET ROLE;

-- ---------------------------------------------------------------------------
-- What actually changed
-- ---------------------------------------------------------------------------
SELECT is(
  (SELECT status FROM public.conflict_resolutions
    WHERE id::text = '22220000-0000-4000-8000-0000000c0001'),
  'ignored',
  'the staff-account conflict was closed by the admin only');

SELECT is(
  (SELECT entity_type FROM public.conflict_resolutions
    WHERE id::text = '22220000-0000-4000-8000-0000000c0001'),
  'app_users',
  'its record type is unchanged');

SELECT is(
  (SELECT status FROM public.conflict_resolutions
    WHERE id::text = '22220000-0000-4000-8000-0000000c0002'),
  'pending',
  'the stock conflict is still open (the nurse''s close was refused)');

SELECT is(
  (SELECT count(*)::int FROM public.conflict_resolutions
    WHERE id::text LIKE '22220000-0000-4000-8000-0000000c0%'),
  15,
  '15 conflicts exist: 3 fixtures, 3 by the admin, 2 by the nurse, 7 by the doctor');

SELECT * FROM finish();
ROLLBACK;
