import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useOperationsQueue } from '@/stores/operationsQueue';
import { QueueListIcon, CheckCircleIcon, ExclamationCircleIcon, ClockIcon } from '@heroicons/react/24/outline';
export function QueueStatus() {
    const queueStore = useOperationsQueue();
    const pendingCount = queueStore.getPendingCount();
    const failedCount = queueStore.getFailedCount();
    const completedOps = queueStore.operations.filter(op => op.status === 'completed');
    if (pendingCount === 0 && failedCount === 0 && completedOps.length === 0) {
        return null;
    }
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-lg p-4 shadow-sm", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(QueueListIcon, { className: "h-5 w-5 text-blue-600" }), _jsx("h3", { className: "font-semibold text-gray-900", children: "Sync Queue" })] }), completedOps.length > 0 && (_jsx("button", { onClick: () => queueStore.clearCompleted(), className: "text-xs text-gray-600 hover:text-gray-900", children: "Clear completed" }))] }), _jsxs("div", { className: "space-y-2", children: [pendingCount > 0 && (_jsxs("div", { className: "flex items-center gap-2 text-sm", children: [_jsx(ClockIcon, { className: "h-4 w-4 text-blue-500" }), _jsxs("span", { className: "text-gray-700", children: [pendingCount, " pending operation", pendingCount !== 1 ? 's' : ''] })] })), queueStore.totalProcessed > 0 && (_jsxs("div", { className: "flex items-center gap-2 text-sm", children: [_jsx(CheckCircleIcon, { className: "h-4 w-4 text-green-500" }), _jsxs("span", { className: "text-gray-700", children: [queueStore.totalProcessed, " synced"] })] })), failedCount > 0 && (_jsxs("div", { className: "flex items-center gap-2 text-sm", children: [_jsx(ExclamationCircleIcon, { className: "h-4 w-4 text-red-500" }), _jsxs("span", { className: "text-gray-700", children: [failedCount, " failed"] }), _jsx("button", { onClick: () => queueStore.retryAllFailed(), className: "ml-auto text-xs text-blue-600 hover:text-blue-800 font-medium", children: "Retry all" })] }))] }), queueStore.isProcessing && (_jsx("div", { className: "mt-3 pt-3 border-t border-gray-200", children: _jsxs("div", { className: "flex items-center gap-2 text-sm text-blue-600", children: [_jsx("div", { className: "animate-spin rounded-full h-4 w-4 border-2 border-blue-600 border-t-transparent" }), _jsx("span", { children: "Processing queue..." })] }) })), (pendingCount > 0 || failedCount > 0) && (_jsx("div", { className: "mt-3 text-xs text-gray-500", children: "Operations will sync automatically when online" }))] }));
}
